### ISSUE TITLE
Page for adding a new Experience

### ISSUE THREAD

**Issue by MLHProgram** [MLH-Fellowship/orientation-project-js-24.FAL.B#11]
Add a page that allows users to add a new Experience which includes the following fields:

- title
- company
- start_date
- end_date
- description
- logo

Collaborate with the fellows contributing to the Python project to understand how logos will be managed. For now, assume this is a string (URL to the image). 

When this information is submitted, a POST request should be made to `/resume/experience` on the server in the following format:

```json
{
    "title": "Software Developer",
    "company": "A Cooler Company",
    "start_date": "October 2022",    
    "end_date": "Present",
    "description": "Writing JavaScript Code",
    "logo": "example-logo.png",
}
```

The server will return a JSON with the position in the list in the following format:
```json
{
"id": 1
}
```

**Comment by citruscai** [comment]
ill take this one

**Comment by citruscai** [comment]
update: finished form, will make PR once satisfied with styling and reaching out to other fellows to make my styling similar to theirs for cohesiveness

**Comment by inhwaS** [comment]
Hey, I would like to work on #6 and can you please invite me over to your repository since you already have "Experience" page?

**Comment by citruscai** [comment]
> Hey, I would like to work on #6 and can you please invite me over to your repository since you already have "Experience" page?

ok no problem

**Comment by citruscai** [comment]
> Hey, I would like to work on #6 and can you please invite me over to your repository since you already have "Experience" page?
just sent the invite
